### ISSUE TITLE
Change the check of a suppressed exit in leiningen.test2junit

### ISSUE THREAD

**Issue by laurentpetit** [ruedigergad/test2junit#1]
Hello,

Starting with Leiningen 2.4.0, when leiningen.core.main/exit-process? is set to false, it will not be possible to rely on the thrown exception message to be hardcoded to the value "Suppressed exit".
Checking the ex-data :exit-code will be the way to ensure it's a suppressed exit, and the exception message may or may not be "Suppressed exit" (when invoked via leiningen.core.main/abort, it will be the message passed as an argument).

My suggestion is to change the test in leiningen.test2junit so that it does not rely on the exception message (which is used for human display, and should be considered an implementation detail), and rather test for the existence of a :exit-code value in the exception data map:

        ; replace these lines
          (let [msg (.getMessage e)]
            (if (not (= msg "Suppressed exit"))
              (println "Caught exception:" e))))))
        ; with these line
        (if-not (:exit-code (ex-data e))
              (println "Caught exception:" e))

**Comment by ruedigergad** [comment]
While I merged the PR, I forgot to close the issue. Closing it now.
