### ISSUE TITLE
File and line is not reported correctly on test failures

### ISSUE THREAD

**Issue by haines** [ruedigergad/test2junit#10]
When running `lein test2junit` with test2junit 1.2.5, the generated XML has `junit.clj:153` as the source of test failures rather than the correct location (i.e. the test file and line number of the assertion).

#### Expected output

```
expected: (= 0 1)
  actual: (not (= 0 1))
      at: my_test.clj:14
```

#### Actual output

```
expected: (= 0 1)
  actual: (not (= 0 1))
      at: junit.clj:153
```

**Comment by ruedigergad** [comment]
Thank you very much for the bug report.
Please excuse the long delay but I have been terribly busy with other things.
I uploaded test2junit version 1.2.6, which solves this problem at least in my environment.
Please check if the test2junit 1.2.6 also solves the issue for you.
