### ISSUE TITLE
Colorized output breaks generated xml

### ISSUE THREAD

**Issue by MichaelBlume** [ruedigergad/test2junit#12]
plumatic/schema prints descriptions of schema violations in yellow. It doesn't check whether it's writing to a TTY when it does this, possibly because checking whether you're writing to a TTY from a JVM is kind of hard. Could test2junit strip out/escape color codes before writing outputs to xml files?

**Comment by ruedigergad** [comment]
Hi,

thank you very much for reporting this.

I implemented a quick fix and uploaded the new version 1.3.1.

I uploaded some example output related to schema:
http://ruedigergad.github.io/test2junit/test-results/html/test2junit/1_schema-tests.html
(Scroll down to the "schema-fn-validation-failing-fn" result.)
Parts of the color codes are still there but the problematic characters are removed.

Please try version 1.3.1 and let me know if this fix is fine for you.



Cheers,

Ruediger

**Comment by MichaelBlume** [comment]
Thanks for the quick response! This solves our problem =)

**Comment by ruedigergad** [comment]
Great! You're welcome. :)
