### ISSUE TITLE
Tests fail silently with no output in the terminal

### ISSUE THREAD

**Issue by syl20bnr** [ruedigergad/test2junit#13]
At my work developers use `lein test` and they have feedback in the console when a test fails. Our CI uses `lein test2junit` and there is no output in the terminal when a test fails. Looking at the `project.clj` I don't see anything particular that's enabled for `lein test`.

1) Is the behavior I described the expected behavior?
2) Do you have any pointer to enable the same level of feedback for `test2junit`?

Thank you.

**Comment by ruedigergad** [comment]
Thanks for your feedback.
Just as a quick reply:
I uploaded test2junit version 1.3.2, which adds improved output.
Please let me know if this fixes the issue for you.
As time permits, I can also add a screenshot.

**Comment by syl20bnr** [comment]
This is excellent ! thank you 👍
