### ISSUE TITLE
NullPointerException with "unconventional" plugin setup

### ISSUE THREAD

**Issue by rborer** [ruedigergad/test2junit#18]
Hi,

I'm encountering the following NPE when I run `test2junit` leiningen goal:

```
java.lang.NullPointerException: null
 at leiningen.test2junit$test2junit.invokeStatic (test2junit.clj:47)
    leiningen.test2junit$test2junit.doInvoke (test2junit.clj:31)
    clojure.lang.RestFn.invoke (RestFn.java:410)
    clojure.lang.Var.invoke (Var.java:379)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$partial_task$fn__4667.doInvoke (main.clj:284)
    clojure.lang.RestFn.invoke (RestFn.java:410)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.RestFn.applyTo (RestFn.java:132)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:29)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$apply_task.invokeStatic (main.clj:334)
    leiningen.core.main$apply_task.invoke (main.clj:320)
    leiningen.core.main$resolve_and_apply.invokeStatic (main.clj:340)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:336)
    leiningen.update_in$update_in.invokeStatic (update_in.clj:37)
    leiningen.update_in$update_in.doInvoke (update_in.clj:24)
```

This is caused by the way I enable the plugin. I have the following in my `~/.lein/profiles.clj`:

```
;; the following aliases turn off :pedantic check before injecting
  ;; the plugin as a dependency, since a plugin dependency interact
  ;; with build dependencies and may cause dependencies to diverge 
  :aliases {"test2junit" ["update-in" ":pedantic?" "nil?"
                          "--"
                          "update-in" ":plugins" "conj" "[test2junit \"1.4.0\"]"
                          "--" "test2junit"]}
```

I have `:pedantic` enabled in most of my projects. Since leiningen fails to distinguish build and plugin dependencies, some plugins I add to my projects makes dependency resolution fails to converge. As such, I am using aliases which selectively disable `:pedantic` and activate the plugin at the same time.

Unfortunately, this makes the code fails to find the plugin version ([at line 47 here](https://github.com/ruedigergad/test2junit/blob/dcf1b089dd2f0ad46456ab1511ed11d4a7c1a6be/src/leiningen/test2junit.clj#L48) ). One solution could be to skip this `println` line when the plugin version cannot be determined.

Although I'm wondering if there isn't a more robust way to get this information through leiningen.

Would you accept a PR to selectively disable this `println` instruction?

**Comment by ruedigergad** [comment]
Hi,

thanks a lot for the bug report and the detailed information.

I just uploaded test2junit version 1.4.1 to Clojars, which hopefully should fix your issue.

Please let me know if this solves your problem so I can close the issue or look for another solution.

Thanks again and cheers,

Ruediger

**Comment by rborer** [comment]
Thanks for the patch!

Now it goes a bit further but it still not working 😢 , here is the output I have now:

```
$ lein test2junit
Retrieving test2junit/test2junit/1.4.1/test2junit-1.4.1.pom from clojars
Retrieving test2junit/test2junit/1.4.1/test2junit-1.4.1.jar from clojars
Using test2junit version: n/a
Could not find artifact test2junit:test2junit:jar:n/a in central (https://repo1.maven.org/maven2/)
Could not find artifact test2junit:test2junit:jar:n/a in clojars (https://repo.clojars.org/)
Could not find artifact test2junit:test2junit:jar:n/a in sonatype (https://oss.sonatype.org/content/repositories/releases)
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```

Since it's trying to re-inject the dependency, you may want to try `LATEST` instead of `N/A`. `LATEST` would in my specific case include the latest available plugin version as a work-around.

Cheers,
Reynald

**Comment by rborer** [comment]
Thanks, it works perfectly fine now 👍 .
