### ISSUE TITLE
Usage examples would be helpful

### ISSUE THREAD

**Issue by tcushman** [ruedigergad/test2junit#4]
I'm having some difficulty trying to figure out how to configure this plugin within a project.clj file.  A sample configuration snippet would be helpful....

Also wondering if this is abandoned.  Reading through the Leiningen plugin development guide suggests that this plugin might not be current with the Leiningen plugin spec since there is no "test2junit.plugin/hooks" function or namespace.

**Comment by ruedigergad** [comment]
Thanks for your feedback.
I added a simple usage example and briefly tested test2junit here and it works.
I am using Leiningen version 2.5.1 and Ant version 1.9.2.
Please also note that if you want to automatically create an HTML report you need to have the junitreport Ant task installed.

**Comment by ruedigergad** [comment]
Closing this as solved.
Please re-open if this is still not sufficiently addressed.
