### ISSUE TITLE
Allow passing output dir as environment variable

### ISSUE THREAD

**Issue by erez-rabih** [ruedigergad/test2junit#8]
The change is small - just need to check if a pre-defined environment variable (JUNIT_OUTPUT_DIR) is set here: https://github.com/ruedigergad/test2junit/blob/master/src/test2junit/core.clj#L29
before going to the default hardcoded value.

I run tests via jenkins so I can't pass the output dir into project.clj

**Comment by ruedigergad** [comment]
Hi,

thanks for your feedback.

I just added more options for setting the output directory.
Now, it is possible to use the environment variable:
TEST2JUNIT_OUTPUT_DIR
and the Java system property:
test2junit.output.dir
to set the output directory.

The order in which these are considered is (from top to down):
  (or
    (System/getenv "TEST2JUNIT_OUTPUT_DIR")
    (System/getProperty "test2junit.output.dir")
    (:test2junit-output-dir project)
    "test2junit")

I pushed a new version 1.2.0 to Clojars.
I hope that you find this change useful.

I briefly tested the change here in fish, but I am leaving this issue open for now, just in case something does not work as expected.
Please close the issue if you see that things work for you as intended.

Cheers,

Ruediger

**Comment by erez-rabih** [comment]
@ruedigergad Thanks for the fast reply.
I will give it a test and post my feedback.

**Comment by erez-rabih** [comment]
I tried supplying the environment variable TEST2JUNIT_OUTPUT_DIR and it looks like everything works as expected.
I didn't try the java system property but I'm closing this issue anyway.
Thanks for the help!
